services:
  franka_ros2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    command: >
      /bin/sh -c "
        cd /third_party/pytorch3d_simplified &&
        find . -name "*.so" -delete || true &&
        CUDA_HOME=/usr/local/cuda CUB_HOME=/opt/cub python3 setup.py build_ext --inplace &&
        pip install -e . &&
        exec tail -f /dev/null
      "
    container_name: base_franka_ros2
    network_mode: "host"
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - ./:/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./limits.conf:/etc/security/limits.conf
      - /dev:/dev
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

