services:
  fr3-docker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_UID=1003
        - USER_GID=1003
    container_name: fr3-docker
    network_mode: "host"
    privileged: true
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - ../fr3-docker:/home/user/fr3-docker
      - /tmp/.X11-unix:/tmp/.X11-unix
      # - ./limits.conf:/etc/security/limits.conf
      - /dev:/dev
      - /etc/udev/rules.d:/etc/udev/rules.d
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
